name: Build APK from BtcNextCandleFull

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip BtcNextCandleFull.zip -d project

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Gradlew permission
        run: chmod +x project/gradlew

      - name: Build APK
        working-directory: project
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
          
